name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Change this if your project uses a different version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope your-vercel-scope
